FocusOnTheFamily/ViewModels/EditContentVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FocusOnTheFamily.ViewModels
{
    public class EditContentVM
    {
        public Models.Content pageContent { get; set; }
        public List<Models.Product> Products { get; set; }
        public List<Models.Image> Images { get; set; }
    }
}

FocusOnTheFamily/ViewModels/EditProductVM.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace FocusOnTheFamily.ViewModels
{
    public class EditProductVM
    {
        public Models.Product product { get; set; }
        public List<Models.Image> images { get; set; }
    }
}

FocusOnTheFamily/Controllers/AdminController.cs
using FocusOnTheFamily.Domain.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FocusOnTheFamily.Controllers
{
    public class AdminController : Controller
    {
        IContentProcessor _contentProcessor;
        IProductProcessor _productProcessor;
        IImageProcessor _imageProcessor;

        public AdminController(IContentProcessor contentProcessor, IProductProcessor productProcessor, IImageProcessor imageProcessor)
        {
            _contentProcessor = contentProcessor;
            _productProcessor = productProcessor;
            _imageProcessor = imageProcessor;
        }

        // GET: Admin
        public ActionResult Index()
        {
            return View();
        }

        // GET: Content
        public ActionResult ListContents()
        {
            List<Models.Content> contents = _contentProcessor.GetContents();

            return View("Content", contents);
        }

        public ActionResult Content(int id)
        {
            ViewModels.EditContentVM contentViewModel = new ViewModels.EditContentVM();

            contentViewModel.pageContent = _contentProcessor.GetPageContent(id);
            contentViewModel.Products = _productProcessor.GetProducts();
            contentViewModel.Images = _imageProcessor.GetImages();

            return View("EditContent", contentViewModel);
        }

        [HttpPost]
        public ActionResult UpdateContentTitle(Models.Content content)
        {
            _contentProcessor.UpdateContent(content);

            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult DeleteContentStory(int ContentStoryID)
        {
            _contentProcessor.DeleteContentStory(ContentStoryID);

            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult UpdateContentStory(Models.ContentStory story)
        {
            _contentProcessor.UpdateContentStory(story);

            return Json(new { success = true });
        }

        [HttpGet]
        public ActionResult ListProducts()
        {
            List<Models.Product> products = _productProcessor.GetProducts();

            return View("ListProducts", products);
        }

        [HttpGet]
        public ActionResult EditProduct(System.Guid id)
        {
            ViewModels.EditProductVM productViewModel = new ViewModels.EditProductVM();

            productViewModel.product = new Models.Product();
            if(id != System.Guid.Empty)
                productViewModel.product = _productProcessor.GetProduct(id);

            productViewModel.images = _imageProcessor.GetImages();

            return View("EditProduct", productViewModel);
        }

        [HttpPost]
        public ActionResult DeleteProductDetail(int ProductDetailID)
        {
            _productProcessor.DeleteProductDetail(ProductDetailID);

            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult UpdateProductDetail(Models.ProductDetail productDetail)
        {
            _productProcessor.UpdateProductDetail(productDetail);

            return Json(new { success = true });
        }

        [HttpPost]
        public ActionResult UpdateProduct(Models.Product product)
        {
            _productProcessor.UpdateProduct(product);

            return Json(new { success = true });
        }
    }
}

FocusOnTheFamily/Controllers/HomeController.cs
using FocusOnTheFamily.Domain.Interfaces;
using FocusOnTheFamily.Domain.Processors;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FocusOnTheFamily.Controllers
{
    public class HomeController : Controller
    {
        private IContentProcessor _contentProcessor;

        public HomeController(IContentProcessor contentProcessor)
        {
            _contentProcessor = contentProcessor;
        }

        // GET: Home
        public ActionResult Index()
        {
            return BuildPageView(1);
        }

        // GET: About
        public ActionResult About()
        {
            return BuildPageView(2);
        }

        // GET: About
        public ActionResult Testimonial()
        {
            return BuildPageView(3);
        }

        private ActionResult BuildPageView(int pageContentID)
        {
            Models.Content pageContent = _contentProcessor.GetPageContent(pageContentID);

            return View("Index", pageContent);
        }
    }
}

FocusOnTheFamily/Controllers/ProductController.cs
using FocusOnTheFamily.Domain.Interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FocusOnTheFamily.Controllers
{
    public class ProductController : Controller
    {
        private IProductProcessor _productProcessor;

        public ProductController(IProductProcessor productProcessor)
        {
            _productProcessor = productProcessor;
        }

        // GET: Product
        public ActionResult Index()
        {
            List<Models.Product> products = _productProcessor.GetProducts();

            return View("Index", products);
        }

        // GET: Detail
        public ActionResult Detail(System.Guid? id)
        {
            Models.Product productDTO = _productProcessor.GetProduct(id);
            List<Models.Product> products = new List<Models.Product>();
            products.Add(productDTO);

            return View("Index", products);
        }
    }
}

FocusOnTheFamily/Views/Admin/Content.cshtml
@model List<FocusOnTheFamily.Models.Content>

@{
    ViewBag.Title = "List Contents";
}

<h2>Select a page to edit</h2>
<hr />

@foreach (FocusOnTheFamily.Models.Content content in @Model)
{
    @Html.ActionLink(@content.Title, "Content", "Admin", new { id = content.ContentID }, new { @class = "btn btn-default btn-sm" })
    <br /><br />
}

FocusOnTheFamily/Views/Admin/EditContent.cshtml
@model FocusOnTheFamily.ViewModels.EditContentVM

@{
    ViewBag.Title = "EditContent";
}

<h2>Edit Content</h2>
<div>
    @Html.ActionLink("Back to List", "ListContents", "Admin")
</div>

<form id="updateContentTitleForm">
    <div class="form-horizontal">
        <hr />
        <input type="hidden" id="ContentID" value="@Model.pageContent.ContentID" />

        <div class="form-group">
            <label for="Title" class="control-label col-md-2">Title</label>
            <input type="text" name="Title" id="Title" class="form-control " value="@Model.pageContent.Title" />
        </div>
        <div class="form-group text-right">
            <input type="button" class="btn btn-primary" onclick="ContentUpdateTitle($('#Title'), $('#ContentID'));" value="Update Title" />
        </div>

        @foreach (FocusOnTheFamily.Models.ContentStory story in Model.pageContent.StoryContent)
        {
            @DisplayStoryData(@story)
        }
        @{ 
            FocusOnTheFamily.Models.ContentStory tmpStory = new FocusOnTheFamily.Models.ContentStory();
            @DisplayStoryData(tmpStory);
        }
    </div>    
</form>

<div>
    @Html.ActionLink("Back to List", "ListContents", "Admin")
</div>

@helper DisplayStoryData(FocusOnTheFamily.Models.ContentStory story)
{
string updateButtonText;
string isSelected = "";

if(story.ContentStoryID > 0)
{
    updateButtonText = "Update Story";
}
else
{
    updateButtonText = "Create Story";
}

    <div class="panel panel-default">
        <div class="panel-body">
            <div class="form-group">
                <label for="StoryTitle-@story.ContentStoryID" class="control-label col-md-2">Title</label>
                <input type="text" id="StoryTitle-@story.ContentStoryID" class="form-control " value="@story.StoryTitle" />
            </div>
            <div class="form-group">
                <textarea id="StoryText-@story.ContentStoryID" class="form-control" style="min-width: 100%;" rows="10" placeholder="Story content here!">@story.StoryText</textarea>
            </div>
            <div class="form-group">
                <label for="ImagePath-@story.ContentStoryID" class="control-label col-md-2">Image Path</label>
                <select id="ImagePath-@story.ContentStoryID" class="form-control">
                    <option value="">---SELECT---</option>
                    @foreach (FocusOnTheFamily.Models.Image image in Model.Images)
                    {
                        if (story.ImagePath == image.ImagePath)
                        {
                            isSelected = " selected='selected' ";
                        }
                        else
                        {
                            isSelected = "";
                        }

                        <option value="@image.ImagePath" @isSelected>@image.ImagePath</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label for="RelatedProductID-@story.ContentStoryID" class="control-label col-md-2">Related Product</label>
                <select id="RelatedProductID-@story.ContentStoryID" class="form-control">
                    <option value="@System.Guid.Empty">---SELECT---</option>
                    @foreach(FocusOnTheFamily.Models.Product product in Model.Products)
                    {
                        if (story.RelatedProductID == product.ProductID)
                        {
                            isSelected = " selected='selected' ";
                        }
                        else
                        {
                            isSelected = "";
                        }

                        <option value="@product.ProductID" @isSelected>@product.Title (@product.ISBN)</option>
                    }
                </select>
            </div>
        </div>
        <div class="panel-footer text-right">
            <input type="button" class="btn btn-primary" onclick="UpdateStory(@Model.pageContent.ContentID, @story.ContentStoryID, $('#StoryTitle-@story.ContentStoryID').val(), $('#StoryText-@story.ContentStoryID').val(), $('#ImagePath-@story.ContentStoryID').val(), $('#RelatedProductID-@story.ContentStoryID').val());" value="@updateButtonText" />
            @if(story.ContentStoryID > 0)
            {
                <input type="button" class="btn btn-danger" onclick="DeleteStory(@story.ContentStoryID);" value="Delete Story" />
            }
        </div>
    </div>
}

FocusOnTheFamily/Views/Admin/EditProduct.cshtml
@model FocusOnTheFamily.ViewModels.EditProductVM

@{
    ViewBag.Title = "EditProduct";
}

<h2>Edit Product</h2>

<div>
    @Html.ActionLink("Back to Product List", "ListProducts", "Admin")
</div>

<form id="updateProductForm">
    <hr />
    <div class="form-horizontal">
        <input type="hidden" id="ProductID" value="@Model.product.ProductID" />

        <div class="form-group">
            <label for="Title" class="control-label col-md-2">Title</label>
            <input type="text" name="Title" id="Title" class="form-control" value="@Model.product.Title" />
        </div>
        <div class="form-group">
            <label for="ISBN" class="control-label col-md-2">ISBN</label>
            <input type="text" name="ISBN" id="ISBN" class="form-control" value="@Model.product.ISBN" />
        </div>
        <div class="form-group">
            <label for="Price" class="control-label col-md-2">Price</label>
            <div class="input-group">
                <span class="input-group-addon">$</span>
                <input type="text" name="Price" id="Price" class="form-control currency" value="@Model.product.Price" />
            </div>
        </div>
        <div class="form-group">
            <label for="QtyAvail" class="control-label col-md-2">Qty</label>
            <input type="text" name="QtyAvail" id="QtyAvail" class="form-control" value="@Model.product.QtyAvail" />
        </div>
        <div class="form-group">
            <label for="Authors" class="control-label col-md-2">Authors</label>
            <input type="text" name="Authors" id="Authors" class="form-control" value="@Model.product.Authors" />
        </div>
        <div class="form-group">
            <label for="ImagePath" class="control-label col-md-2">Image Path</label>
            <select id="ImagePath" class="form-control">
                <option value="">---SELECT---</option>
                @foreach (FocusOnTheFamily.Models.Image image in Model.images)
                {
                    string isSelected = "";
                    if (Model.product.ImagePath == image.ImagePath)
                    {
                        isSelected = " selected='selected' ";
                    }
                    else
                    {
                        isSelected = "";
                    }

                    <option value="@image.ImagePath" @isSelected>@image.ImagePath</option>
                }
            </select>

        </div>
        <div class="form-group">
            <label for="Summary" class="control-label col-md-2">Summary</label>
            <textarea id="Summary" class="form-control" style="min-width: 100%;" rows="10" placeholder="Product Summary!">@Model.product.Summary</textarea>
        </div>
        <div class="form-group">
            <label for="Description" class="control-label col-md-2">Description</label>
            <textarea id="Description" class="form-control" style="min-width: 100%;" rows="10" placeholder="Product Descriptions!">@Model.product.Description</textarea>
        </div>
        <div class="form-group text-right">
            <input type="button" class="btn btn-primary" onclick="UpdateProduct();" value="Update Product" />
        </div>
    </div>
    <hr />

    @{
        if (Model.product.ProductID != System.Guid.Empty)
        {
            <h4>Product Details</h4>
            foreach(FocusOnTheFamily.Models.ProductDetail detail in Model.product.ProductDetails)
            {
                @DisplayDetailRow(detail)
            }
            @DisplayDetailRow(new FocusOnTheFamily.Models.ProductDetail())
        }
    }
</form>

@helper DisplayDetailRow(FocusOnTheFamily.Models.ProductDetail detail)
{
string detailTitleID = "DetailTitle-" + @detail.ProductDetailID;
string detailSummaryID = "DetailSummary-" + @detail.ProductDetailID;
    <div class="panel">
        <div class="panel-body">
            <div class="form-group">
                <label for="@detailTitleID" class="control-label col-md-2 text-right">Title</label>
                <input type="text" id="@detailTitleID" class="form-control" value="@detail.DetailTitle" />
            </div>
            <div class="form-group">
                <label for="@detailSummaryID" class="control-label col-md-2 text-right">Summary</label>
                <input type="text" id="@detailSummaryID" class="form-control" value="@detail.DetailSummary" />
            </div>
            <div class="form-group text-right">
                <input type="button" class="btn btn-primary" onclick="UpdateProductDetail('@Model.product.ProductID', @detail.ProductDetailID, $('#@detailTitleID').val(), $('#@detailSummaryID').val());" value="Save" />
                @{
                    if (detail.ProductDetailID != 0)
                    {
                        <input type="button" class="btn btn-danger" onclick="DeleteProductDetail(@detail.ProductDetailID);" value="Delete" />
                    }
                }
            </div>
        </div>
    </div>
}

FocusOnTheFamily/Views/Admin/Index.cshtml
@{
    ViewBag.Title = "Administration";
}

<h3>Administator Options</h3>
<p>Select an option on the top menu</p>

FocusOnTheFamily/Views/Admin/ListProducts.cshtml
@model List<FocusOnTheFamily.Models.Product>

@{
    ViewBag.Title = "ListProducts";
}

<h2>Select a product to edit</h2>
<hr />

@foreach (FocusOnTheFamily.Models.Product product in @Model)
{
    @DisplayEditProductLink(@product.Title, product.ProductID)
    <br /><br />
}

<hr />
<!--@DisplayEditProductLink("Add New Product", System.Guid.Empty)-->


@helper DisplayEditProductLink(string title, System.Guid productID)
{
    @Html.ActionLink(@title, "EditProduct", "Admin", new { id = productID }, new { @class = "btn btn-default btn-sm" })
}

FocusOnTheFamily/Views/Home/Index.cshtml
@model FocusOnTheFamily.Models.Content


@{
    ViewBag.Title = Model.Title;
}

@{
    int rowCount = 0;
    string imgClass = "";
    string contentTitleClass = "";
}

<div class="container">
    @foreach (FocusOnTheFamily.Models.ContentStory story in Model.StoryContent)
    {
        rowCount++;
        if (rowCount % 2 != 0)
        {
            imgClass = "pull-right";
            contentTitleClass = "text-left";
        }
        else
        {
            imgClass = "pull-left";
            contentTitleClass = "text-right";
        }
        
        <div class="row">
            <div class="col-sm-1"></div>
            <div class="col-sm-10">
                <div class="@contentTitleClass gap">
                    <h1>@story.StoryTitle</h1>
                </div>
                @if (story.ImagePath != "")
                {
                    <img src="@story.ImagePath" class="@imgClass img-rounded img-responsive gap" />
                }
                <p class="gap">
                    @story.StoryText
                </p>
                @if (story.RelatedProductID != System.Guid.Empty)
                {
                    @Html.ActionLink("I want to know more!", "Detail", "Product", new { id = story.RelatedProductID }, new { @class = "btn btn-default btn-sm" })
                }
            </div>
            <div class="col-sm-1"></div>
        </div>
        <div class="container-fluid">
            <hr />
        </div>
    }
</div>

FocusOnTheFamily/Views/Product/Index.cshtml
@model List<FocusOnTheFamily.Models.Product>

@{
    ViewBag.Title = "Products";
}

@{
    int rowCount = 0;
    string imgClass = "";
    string contentTitleClass = "";
    string productDetailPanelID = "";
}


<div class="container">
    @foreach (FocusOnTheFamily.Models.Product product in Model)
    {
        rowCount++;
        if (rowCount % 2 != 0)
        {
            imgClass = "pull-right";
            contentTitleClass = "text-left";
        }
        else
        {
            imgClass = "pull-left";
            contentTitleClass = "text-right";
        }

        <div class="row">
            <div class="col-sm-2"></div>
            <div class="col-sm-8">
                <div class="@contentTitleClass gap">
                    <h1>@product.Title</h1>
                    <h5>@product.Authors</h5>
                </div>
                @if (product.ImagePath != "")
                {
                    <img src="@product.ImagePath" class="@imgClass img-rounded gap" />
                }
                <h5>@product.Summary</h5>
                <p class="gap">
                    @product.Description
                </p>
                <br />
                @{
                    productDetailPanelID = "product-details-" + @product.ProductID;
                }

                @if (product.ProductDetails.Count() > 0)
                {
                    <div class="panel-group">
                        <div class="panel panel-default">
                            <div class="panel-header">
                                <h4 class="panel-title">
                                    <a data-toggle="collapse" href="#@(productDetailPanelID) ">Product Details</a>
                                </h4>
                            </div>
                            <div id="@productDetailPanelID" class="panel-collapse collapse">
                                <div class="paenl-body">
                                    <ul>
                                        @foreach (FocusOnTheFamily.Models.ProductDetail detail in product.ProductDetails)
                                        {
                                            <li>
                                                @detail.DetailTitle
                                                <p>
                                                    @detail.DetailSummary
                                                </p>
                                            </li>
                                        }
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
            <div class="col-sm-2"></div>
        </div>
        <div class="container-fluid">
            <hr />
        </div>
    }
</div>

FocusOnTheFamily/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewBag.Title - Ready to Wed!</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="~/scripts/Site.js"></script>
</head>
<body>
    @RenderTopNavigation()

    <div class="container body-content">
        @RenderBody()
        @RenderFooter()
    </div>

    @BuildAdminPrompt()

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

@functions{
    public string GetFOTFIcon()
    {
        return "/Content/Images/fotf_icon.jpg";
    }
}

@helper RenderFooter()
{
    <hr />
    <footer>
        <p>&copy; @DateTime.Now.Year Focus on the Family Ministries</p>
    </footer>
}

@helper RenderTopNavigation()
{
    if (@HttpContext.Current.Request.RequestContext.RouteData.Values["controller"].ToString().ToUpper() == "ADMIN")
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#headerNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                        <img src="@GetFOTFIcon()" style="height: 30px;border: 0px;" />
                        Focus on the Family
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="headerNavBar">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Edit Pages", "ListContents", "Admin")</li>
                        <li>@Html.ActionLink("Edit Products", "ListProducts", "Admin")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("Logout", "Index", "Home", new { }, new { @class="glyphicon glyphicon-user"});
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    }
    else
    {
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#headerNavBar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a href="@Url.Action("Index", "Home")" class="navbar-brand">
                        <img src="@GetFOTFIcon()" style="height: 30px;border: 0px;" />
                        Focus on the Family
                    </a>
                </div>
                <div class="navbar-collapse collapse" id="headerNavBar">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About Ministry", "About", "Home")</li>
                        <li>@Html.ActionLink("Testimonials", "Testimonial", "Home")</li>
                        <li>@Html.ActionLink("Products", "Index", "Product")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            @Html.ActionLink("Admin Login", "Index", "Admin", new { }, new { @class = "glyphicon glyphicon-user" });
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    }
}

@helper BuildAdminPrompt()
{
    <div class="modal fade" id="admin-login-modal">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title">Admin Login Portal</h4>
                </div>
                <div class="modal-content" style="padding-left: 35px;">
                    <div class="container">
                        <form id="adminLoginForm">
                            <div class="form-horizontal">
                                <div class="form-group">
                                    <label for="username">User Name</label>
                                    <input type="text" class="form-control" id="username" name="username" placeholder="User Name" />
                                </div>
                                <div class="form-group">
                                    <label for="pswd">Password</label>
                                    <input type="password" class="form-control" id="pswd" name="pswd" placeholder="Password" />
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary">Login</button>
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
}